services:
  # app:
  #   build:
  #     context: .
  #     args:
  #       NODE_ENV: ${NODE_ENV}
  #   ports:
  #     - '3001:3000'
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: ${DB_PORT}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     DATABASE_URL: ${DATABASE_URL}
  # volumes:
  #   - ./:/app
  #   - /app/node_modules
  # command: npm run start:dev
  # depends_on:
  #   - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5433:5432'
